## Use https://github.com/sj26/rspec_junit_formatter to generate a JUnit report format XML file with rspec
image: maven:latest

stages:
  - compile
  - tests

backend-compile:
  stage: compile
  script:
    - mvn -f api/pom.xml clean install
    - mvn -f api/pom.xml clean compile

backend-compile-tests:
  stage: compile
  script:
    - mvn -f api/pom.xml clean install
    - mvn -f api/pom.xml clean test-compile

backend-unit-tests:
  stage: tests
  needs: ["backend-compile-tests"]
  script:
    - mvn -f api/pom.xml clean test

backend-system-test:
  stage: tests
  needs: ["backend-compile"]
  script:
    - wget "https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.2.zip" -q -O glassfish
    - apt update
    - apt install unzip
    - unzip -q glassfish
    - mvn -f api/pom.xml clean package
    - mv /builds/sestakp/but-fit-pis/api/target/* glassfish7/glassfish/domains/domain1/applications/
    - unzip glassfish7/glassfish/domains/domain1/applications/*.war
    - glassfish7/glassfish/bin/asadmin start-domain